# Generated by Django 4.2.6 on 2023-12-10 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'flash',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
