# Generated by Django 4.2.6 on 2023-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_flash_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flash',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='flash',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='flash',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
